# 应用名称
spring:
  application:
    # 应用名称
    name: SpringAiStar

  ai:
    ollama:
      # Ollama服务的基础URL
      base-url: http://localhost:11434

      chat:
        # 启用聊天功能
        enabled: true
        options:
          # 使用的模型
          model: qwen2
          # 温度：用于调节生成文本的多样性的温度参数。默认值为0.8
          temperature: 0.8
          # 上下文数量
          num-ctx: 2048
          # 线程数量
          num-thread: 8
          # 输出格式：指定聊天结果的输出格式。当前唯一接受的值为 json
          # format: json
          # 保持连接活动的时间：控制模型在请求后加载到内存中的时间。默认值为5分钟
          # keep_alive: 5m
          # 是否使用NUMA：控制是否使用非均匀内存访问架构。默认值为false
          # numa: false
          # 批量大小：每次推理请求中的输入批量大小。默认值为512
          # num-batch: 512
          # GPU数量：要发送到GPU的层数。默认值为-1表示自动选择
          # num-gpu: -1
          # 主GPU设备：指定主要使用的GPU设备编号或名称。默认值为空
          # main-gpu: -
          # 低VRAM模式：是否启用低VRAM模式。默认值为false
          # low-vram: false
          # 使用f16 kv：是否使用f16计算精度。默认值为true
          # f16-kv: true
          # 是否记录所有logits：是否记录所有的logits值。默认值为false
          # logits-all: false
          # 仅限于词汇表：是否仅使用词汇表中的单词进行推理。默认值为false
          # vocab-only: false
          # 使用内存映射：是否使用内存映射来加速数据访问。默认值为true
          # use-mmap: true
          # 锁定内存：是否锁定内存以提高性能。默认值为false
          # use-mlock: false
          # 保留数量：每个对话上下文中保留的历史输入数量。默认值为0
          # num-keep: 0
          # 随机种子：设置用于生成的随机数种子。默认值为-1表示使用系统默认值
          # seed: -1
          # 预测数量：每次推理请求中的预测数量。默认值为-1表示自动选择
          # num-predict: -1
          # Top-k值：用于减少生成无意义文本的概率。默认值为40
          # top-k: 40
          # Top-p值：与Top-k一起工作，用于控制生成文本的多样性。默认值为0.9
          # top-p: 0.9
          # TFS Z值：用于抑制未知输出的参数。默认值为1.0
          # tfs-z: 1.0
          # 典型P值：用于控制输出文本的一致性和多样性。默认值为1.0
          # typical-p: 1.0
          # 重复上次n值：设置模型查看以防止重复的历史输入的数量。默认值为64
          # repeat-last-n: 64
          # 重复惩罚：用于抑制重复文本生成的惩罚参数。默认值为1.1
          # repeat-penalty: 1.1
          # 存在惩罚：用于抑制生成包含特定单词的文本的惩罚参数。默认值为0.0
          # presence-penalty: 0.0
          # 频率惩罚：用于抑制频繁生成某些单词的惩罚参数。默认值为0.0
          # frequency-penalty: 0.0
          # Mirostat：启用Mirostat采样以控制困惑度。默认值为0（禁用）
          # mirostat: 0
          # Mirostat Tau值：控制输出一致性和多样性之间的平衡。默认值为5.0
          # mirostat-tau: 5.0
          # Mirostat Eta值：影响算法对生成文本反馈的响应速度。默认值为0.1
          # mirostat-eta: 0.1
          # 换行符惩罚：是否惩罚生成换行符的参数。默认值为true
          # penalize-newline: true
          # 停止标志：设置停止生成文本的模式。默认值为空
          # stop: -

      # 启用嵌入功能
      embedding:
        enabled: true

  datasource:
    hikari:
      # 最大连接池大小
      maximum-pool-size: 20
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接的超时时间（毫秒）
      idle-timeout: 30000
      # 连接的最大生命周期（毫秒）
      max-lifetime: 1800000
      # 连接超时时间（毫秒）
      connection-timeout: 30000

    # 数据库URL
    url: jdbc:postgresql://localhost:5432/aistar
    # 数据库用户名
    username: aistar_user
    # 数据库密码
    password: 12345
    # 数据库驱动类名
    driver-class-name: org.postgresql.Driver

  security:
    user:
      # Spring Security 用户名
      name: star
      # Spring Security 密码
      password: aistar
      # Spring Security 角色
      roles: USER

logging:
  level:
    io:
      # JSON Web Token (JWT) 的调试日志级别
      jsonwebtoken: DEBUG
    # Spring Security 的调试日志级别（注释掉）
    # org:
    #   springframework:
    #     security: DEBUG
    com:
      # 本地 AI Star 应用的调试日志级别
      localaihub:
        aistar: DEBUG
  file:
    # 日志文件名称
    name: logs/ollama.log
  # 根日志级别
  root: INFO

server:
  servlet:
    encoding:
      # 字符编码
      charset: UTF-8
      # 是否启用编码
      enabled: true
      # 是否强制使用指定编码
      force: true
  port: 15181

jwt:
  # JWT 密钥
  secret: 3xj8FbVQX4P6Fe0Zp+9L3utWZKZY1Dm+bo4Wl1+NiEMCM3QqfMaWmrZbgOQkSYc9Hb1fvCk0YFAqS+CnD6ABaw==
  # JWT 有效期（10小时，单位：毫秒）
  expiration: 36000000

jpa:
  hibernate:
    # Hibernate DDL 自动化策略
    ddl-auto: update
  # 显示SQL语句
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

mybatis-plus:
  # MyBatis Plus 映射文件位置
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      table-underline: true

springdoc:
  api-docs:
    # API 文档路径
    path: /v3/api-docs
  swagger-ui:
    # Swagger UI 路径
    path: /swagger-ui.html
